In [5]:
# import packages
import pandas as pd
import duckdb

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.expand_frame_repr",False)

In [6]:
# connect database
from pipelines.tasks.config.common import DUCKDB_FILE
con = duckdb.connect(database=DUCKDB_FILE, read_only=True)

In [7]:
# Liste des tables
db_tables = con.sql("SHOW TABLES").df() # Afficher le DataFrame 
print(db_tables)

                       name
0   ana__resultats_communes
1              cog_communes
2              edc_communes
3          edc_prelevements
4             edc_resultats
5          laposte_communes
6        mapping_categories
7         stg_communes__cog
8     stg_communes__laposte
9         stg_edc__communes
10  stg_edc__prevelevements
11       stg_edc__resultats

In [ ]:
#view table edc_communes
edc_communes_show = con.execute("SELECT * FROM edc_communes LIMIT 2").fetchdf()
edc_communes_show

  inseecommune                  nomcommune quartier   cdreseau                 nomreseau  debutalim  de_partition de_ingestion_date de_dataset_datetime
0        01001  ABERGEMENT-CLEMENCIAT (L')        -  001000556  BDS ST DIDIER/CHALARONNE 2010-09-07          2024        2025-02-28     20250203-075802
1        01002    ABERGEMENT-DE-VAREY (L')        -  001000369     L'ABERGEMENT-DE-VAREY 2010-09-07          2024        2025-02-28     20250203-075802

In [ ]:
#view table edc_prelevements
edc_prelevements_show = con.execute("SELECT * FROM edc_prelevements LIMIT 2").fetchdf()
edc_prelevements_show

  cddept   cdreseau inseecommuneprinc nomcommuneprinc cdreseauamont nomreseauamont pourcentdebit referenceprel   dateprel heureprel                                                                                           conclusionprel                             ugelib                                                   distrlib                                                     moalib plvconformitebacterio plvconformitechimique plvconformitereferencebact plvconformitereferencechim  de_partition de_ingestion_date de_dataset_datetime
0    001  001000003             01007        AMBRONAY          None           None          None   00100139034 2024-01-23     11h27            Eau d'alimentation conforme aux limites de qualité et non conforme aux références de qualité.  SYND. EAUX REGION D'AMBERIEU-EN-B  SERA - SYNDICAT DES EAUX DE LA REGION D'AMBERIEU-EN-BUGEY  SERA - SYNDICAT DES EAUX DE LA REGION D'AMBERIEU-EN-BUGEY                     C                     C                          N                          C          2024        2025-02-28     20250203-075802
1    001  001000003             01007        AMBRONAY          None           None          None   00100139393 2024-02-13     12h49  Eau d'alimentation conforme aux exigences de qualité en vigueur pour l'ensemble des paramètres mesurés.  SYND. EAUX REGION D'AMBERIEU-EN-B  SERA - SYNDICAT DES EAUX DE LA REGION D'AMBERIEU-EN-BUGEY  SERA - SYNDICAT DES EAUX DE LA REGION D'AMBERIEU-EN-BUGEY                     C                     C                          C                          C          2024        2025-02-28     20250203-075802

In [18]:
#view table edc_resultats
edc_resultats_show = con.execute("SELECT * FROM edc_resultats  ORDER BY referenceprel LIMIT 10").fetchdf()
edc_resultats_show

  cddept referenceprel cdparametresiseeaux  cdparametre              libmajparametre              libminparametre libwebparametre qualitparam insituana                     rqana cdunitereferencesiseeaux cdunitereference limitequal     refqual  valtraduite    casparam referenceanl  de_partition de_ingestion_date de_dataset_datetime
0    001   00100138503             ALTMICR         1370         ALUMINIUM TOTAL µG/L         Aluminium total µg/l            None           N         L                       <10                     µg/L              133       None  <=200 µg/L         0.00   7429-90-5  00100147233          2024        2025-02-28     20250203-075802
1    001   00100138503                 ASP         6489          ASPECT (QUALITATIF)          Aspect (qualitatif)            None           O         L             Aspect normal               SANS OBJET                X       None        None         0.00        None  00100147232          2024        2025-02-28     20250203-075802
2    001   00100138503                 ASP         6489          ASPECT (QUALITATIF)          Aspect (qualitatif)            None           O         L             Aspect normal               SANS OBJET                X       None        None         0.00        None  00100147233          2024        2025-02-28     20250203-075802
3    001   00100138503              CL2LIB         1398                 CHLORE LIBRE                 Chlore libre            None           N         T                      0,30                mg(Cl2)/L              165       None        None         0.30        None         None          2024        2025-02-28     20250203-075802
4    001   00100138503              CL2TOT         1399                 CHLORE TOTAL                 Chlore total            None           N         T                      0,34                mg(Cl2)/L              165       None        None         0.34        None         None          2024        2025-02-28     20250203-075802
5    001   00100138503                CLO2         1754  BIOXYDE DE CHLORE MG/L CLO2  Bioxyde de chlore mg/L ClO2            None           N         T                      N.M.                     mg/L              162       None        None          NaN  10049-04-4         None          2024        2025-02-28     20250203-075802
6    001   00100138503               COULQ         5900         COULEUR (QUALITATIF)         Couleur (qualitatif)            None           O         T  Aucun changement anormal               SANS OBJET                X       None        None         0.00        None         None          2024        2025-02-28     20250203-075802
7    001   00100138503                 FET         1393                    FER TOTAL                    Fer total            None           N         L                        10                     µg/L              133       None  <=200 µg/L        10.00   7439-89-6  00100147232          2024        2025-02-28     20250203-075802
8    001   00100138503                  O3         1746                        OZONE                        Ozone            None           N         T                      N.M.                     mg/L              162       None        None          NaN  10028-15-6         None          2024        2025-02-28     20250203-075802
9    001   00100138503                 ODQ         5901           ODEUR (QUALITATIF)           Odeur (qualitatif)            None           O         L  Aucun changement anormal               SANS OBJET                X       None        None         0.00        None  00100147232          2024        2025-02-28     20250203-075802

In [11]:
#view table mapping_categories
table_check = con.sql("SELECT * FROM mapping_categories LIMIT 10").df()
table_check.head(2)

  cdparametresiseeaux  cdparametre                libmajparametre                libminparametre   casparam   categorie
0              PESTOT         6276  TOTAL DES PESTICIDES ANALYSÉS  Total des pesticides analysés       None  pesticides
1                ATRZ         1107                       ATRAZINE                       Atrazine  1912-24-9  pesticides

In [123]:
#view table mapping_categories paramètre unique
table_check_unique_param_show = con.sql("SELECT cdparametre, cdparametresiseeaux, categorie, COUNT(cdparametresiseeaux) OVER () FROM mapping_categories").df()
print(table_check_unique_param_show)

      cdparametre cdparametresiseeaux   categorie  count(cdparametresiseeaux) OVER ()
0            6276              PESTOT  pesticides                                1611
1            1107                ATRZ  pesticides                                1611
2            1263                 SMZ  pesticides                                1611
3            1221                 MTC  pesticides                                1611
4            1268                 TBZ  pesticides                                1611
...           ...                 ...         ...                                 ...
1607         7850                TC2P  non classé                                1611
1608         2910              BDE183  non classé                                1611
1609         1921               PBDE1  non classé                                1611
1610         2641               DEGBE  non classé                                1611
1611         1420                   Q  non classé                                1611

[1612 rows x 4 columns]

In [124]:
#view table mapping_categories verification des  cdparametresiseeaux non unique
query_map_unique = """
WITH duplicate_count AS (
SELECT cdparametre, cdparametresiseeaux, categorie, COUNT( cdparametresiseeaux) AS count_param
FROM mapping_categories
GROUP BY cdparametresiseeaux, cdparametre, categorie )
,
param_sup2 AS (SELECT * FROM duplicate_count
WHERE count_param > 1
ORDER BY cdparametresiseeaux)

SELECT *
FROM mapping_categories
WHERE cdparametresiseeaux IN (SELECT cdparametresiseeaux
                                FROM param_sup2)
ORDER BY cdparametresiseeaux

"""

table_check_dupliate_show = con.sql(query_map_unique).df()
table_check_dupliate_show

# cdparametre contient 61 lignes vides
# cdparametresiseeaux contient 1 ligne vide

   cdparametresiseeaux  cdparametre                                 libmajparametre                                                         libminparametre      casparam                  categorie
0                ANTXA         7550                              ANATOXINE A TOTALE                                                      Anatoxine A totale    64285-06-9                   microbio
1                ANTXA         7550                            ANATOXINES A TOTALES                                                    Anatoxines A totales    64285-06-9                   microbio
2                 AUSN         7719                                            AUSN  2-[(carbamimidoylcarbamoyl)sulfamoyl]-N,Ndimethylpyridine-3-carboxamid  2307738-55-0    métabolite de pesticide
3                 AUSN         7719                                            AUSN  2-[(carbamimidoylcarbamoyl)sulfamoyl]-N,Ndimethylpyridine-3-carboxamid          None    métabolite de pesticide
4                   CL         1337                                       CHLORURES                                                               Chlorures          None  sous produit désinfection
5                   CL         1337                                       CHLORURES                                                               Chlorures    16887-00-6  sous produit désinfection
6              CLTHALS         7717                          CHLOROTHALONIL R417888                                                  Chlorothalonil R417888  1418095-02-9    métabolite de pesticide
7              CLTHALS         7717                               CHLOROTHALONIL SA                                                       Chlorothalonil SA  1418095-02-9    métabolite de pesticide
8              CYANO53         <NA>                                    JAAGINEMA SP                                                                    None          None                   microbio
9              CYANO53         <NA>                                    JAAGINEMA SP                                                            Jaaginema sp          None                   microbio
10              CYSPPS         7552                      CYLINDROSPERMOPSINE TOTALE                                              Cylindrospermopsine totale   143545-90-8                   microbio
11              CYSPPS         7552                    CYLINDROSPERMOPSINES TOTALES                                            Cylindrospermopsines totales   143545-90-8                   microbio
12             GIARDIA         1064                                     GIARDIA SPP                                                             Giardia spp          None                   microbio
13             GIARDIA         1064                                   AMIBE GIARDIA                                                           Amibe giardia          None                   microbio
14             IMAZAQU         2860                                      IMIZAQUINE                                                              Imizaquine    81335-37-7                 pesticides
15             IMAZAQU         2860                                      IMAZAQUINE                                                              Imazaquine    81335-37-7                 pesticides
16             MCTOAEL         6278  TOTAL DES MICROCYSTINES ANALYSÉES - TEST ELISA                          Total des microcystines analysées - test ELISA          None                   microbio
17             MCTOAEL         6278             MICROCYSTINES ANALYSÉES -TEST ELISA                                     Microcystines analysées -test ELISA          None                   microbio
18               MCTOT         6278               SOMME DES MICROCYSTINES ANALYSÉES                                       Somme des microcystines analysées          None                   microbio
19               MCTOT         6278      SOMME DES MICROCYSTINES ANALYSÉES (CALCUL)                              Somme des microcystines analysées (calcul)          None                   microbio
20                 NO2         1339                               NITRITES (EN NO2)                                                       Nitrites (en NO2)          None                    nitrite
21                 NO2         1339                               NITRITES (EN NO2)                                                       Nitrites (en NO2)    14797-65-0                    nitrite
22                 NO3         1340                               NITRATES (EN NO3)                                                       Nitrates (en NO3)          None                    nitrite
23                 NO3         1340                               NITRATES (EN NO3)                                                       Nitrates (en NO3)    14797-55-8                    nitrite
24                PFOS         6561             ACIDE SULFONIQUE DE PERFLUOROOCTANE                                     Acide sulfonique de perfluorooctane     1763-23-1                       pfas
25                PFOS         6561                    SULFONATE DE PERFLUOROOCTANE                                            Sulfonate de perfluorooctane    45298-90-6                       pfas
26               PPCBS         5602                         PROPOXYCARBAZONE-SODIUM                                                 Propoxycarbazone-sodium   181274-15-7                 pesticides
27               PPCBS         5602                                PROPOXYCARBAZONE                                                        Propoxycarbazone   181274-15-7                 pesticides
28               SAXIT         7551                               SAXITOXINE TOTALE                                                       Saxitoxine totale    35523-89-8                   microbio
29               SAXIT         7551                             SAXITOXINES TOTALES                                                     Saxitoxines totales    35523-89-8                   microbio
30                URAN         1361                                 URANIUM EN ΜG/L                                                         Uranium en µg/l     7440-61-1                 non classé
31                URAN         1361                URANIUM EN MICROGRAMME PAR LITRE                                                         Uranium en µg/l     7440-61-1                 non classé

In [ ]:
#join edc_resultat avec mapping_categories avec distinct cdparametresiseau
query_mapped_edc_resultats = """
SELECT edc_resultats.*, mapping.categorie
FROM edc_resultats
LEFT JOIN (SELECT DISTINCT cdparametresiseeaux, categorie FROM mapping_categories) AS mapping
ON edc_resultats.cdparametresiseeaux = mapping.cdparametresiseeaux
LIMIT 5
"""
mapped_edc_resultats_show = con.sql(query_mapped_edc_resultats).fetchdf()
mapped_edc_resultats_show

  cddept referenceprel cdparametresiseeaux  cdparametre              libmajparametre              libminparametre libwebparametre qualitparam insituana                     rqana cdunitereferencesiseeaux cdunitereference limitequal     refqual  valtraduite    casparam referenceanl  de_partition de_ingestion_date de_dataset_datetime                  categorie
0    001   00100138503             ALTMICR         1370         ALUMINIUM TOTAL µG/L         Aluminium total µg/l            None           N         L                       <10                     µg/L              133       None  <=200 µg/L          0.0   7429-90-5  00100147233          2024        2025-02-28     20250203-075802                    minéral
1    001   00100138503              CL2LIB         1398                 CHLORE LIBRE                 Chlore libre            None           N         T                      0,30                mg(Cl2)/L              165       None        None          0.3        None         None          2024        2025-02-28     20250203-075802  sous produit désinfection
2    001   00100138503                CLO2         1754  BIOXYDE DE CHLORE MG/L CLO2  Bioxyde de chlore mg/L ClO2            None           N         T                      N.M.                     mg/L              162       None        None          NaN  10049-04-4         None          2024        2025-02-28     20250203-075802  sous produit désinfection
3    001   00100138503               COULQ         5900         COULEUR (QUALITATIF)         Couleur (qualitatif)            None           O         T  Aucun changement anormal               SANS OBJET                X       None        None          0.0        None         None          2024        2025-02-28     20250203-075802   paramètre organoleptique
4    001   00100138503                 FET         1393                    FER TOTAL                    Fer total            None           N         L                        10                     µg/L              133       None  <=200 µg/L         10.0   7439-89-6  00100147232          2024        2025-02-28     20250203-075802                    minéral

In [47]:
#verif nombre de ligne après mapping entre edc_resultats et mapping_categories
count_mapped_edc_resultats = """
WITH MAPPED_EDC_RESULTATS AS (SELECT edc_resultats.*, mapping.categorie
FROM edc_resultats
LEFT JOIN (SELECT DISTINCT cdparametresiseeaux, categorie FROM mapping_categories) AS mapping
ON edc_resultats.cdparametresiseeaux = mapping.cdparametresiseeaux)

SELECT 
    CASE 
        WHEN Count(*)  = (SELECT count(*) FROM mapped_edc_resultats)
        THEN 'OK' 
        ELSE 'KO'
    END AS Comparaison
FROM edc_resultats

"""
nb_mapped_edc_resultats = con.sql(count_mapped_edc_resultats)
nb_mapped_edc_resultats

┌─────────────┐
│ Comparaison │
│   varchar   │
├─────────────┤
│ OK          │
└─────────────┘

In [100]:
#nombre de résultats par prélévements
query_resultat_parcatégorie_par_pvl = """
WITH MAPPED_EDC_RESULTATS AS (
SELECT edc_resultats.*, mapping.categorie
FROM edc_resultats
LEFT JOIN (SELECT DISTINCT cdparametresiseeaux, categorie FROM mapping_categories) AS mapping
ON edc_resultats.cdparametresiseeaux = mapping.cdparametresiseeaux)
,
LAST_PREL AS ( 
SELECT cdreseau, referenceprel, MAX(dateprel) AS dernierdateplv, plvconformitebacterio, plvconformitechimique, 
        plvconformitereferencebact, plvconformitereferencechim
FROM edc_prelevements
WHERE cdreseauamont IS NULL
GROUP BY cdreseau, referenceprel, plvconformitebacterio, plvconformitechimique, 
        plvconformitereferencebact, plvconformitereferencechim
ORDER BY referenceprel, dernierdateplv)
,
TEMP_RESULTS AS ( 
SELECT referenceprel, categorie, referenceanl, cdparametresiseeaux,rqana, limitequal, refqual, valtraduite 
FROM MAPPED_EDC_RESULTATS
ORDER BY referenceprel, categorie )
,
NB_RESULT_PAR_PLV AS (
SELECT referenceprel, COUNT(DISTINCT categorie) AS nbcategorieparplv
FROM TEMP_RESULTS
GROUP BY referenceprel
ORDER BY nbcategorieparplv DESC)

SELECT *
FROM NB_RESULT_PAR_PLV
LIMIT 10
"""

nb_resultats_par_plv = con.sql(query_resultat_parcatégorie_par_pvl).to_df()
nb_resultats_par_plv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  referenceprel  nbcategorieparplv
0   05000181555                 16
1   05000181033                 16
2   05000179631                 16
3   05000182111                 16
4   05000178984                 16
5   05000179043                 16
6   05800081917                 15
7   05000180076                 15
8   05800083550                 15
9   05000180338                 15

In [126]:
#récupération résultat dernier prélévement
query_nb_resultat_dernier_plv = """
WITH 
MAPPED_EDC_RESULTATS AS (
SELECT edc_resultats.*, mapping.categorie
FROM edc_resultats
LEFT JOIN (SELECT DISTINCT cdparametresiseeaux, categorie FROM mapping_categories) AS mapping
ON edc_resultats.cdparametresiseeaux = mapping.cdparametresiseeaux)
,
LAST_PREL AS ( 
SELECT cdreseau, referenceprel, MAX(dateprel) AS dernierdateplv, plvconformitebacterio, plvconformitechimique, 
        plvconformitereferencebact, plvconformitereferencechim
FROM edc_prelevements
WHERE cdreseauamont IS NULL
GROUP BY cdreseau, referenceprel, plvconformitebacterio, plvconformitechimique, 
        plvconformitereferencebact, plvconformitereferencechim
ORDER BY referenceprel, dernierdateplv)
,
TEMP_RESULTS AS ( 
SELECT referenceprel, categorie, referenceanl, cdparametresiseeaux,rqana, limitequal, refqual, valtraduite 
FROM MAPPED_EDC_RESULTATS
ORDER BY referenceprel, categorie )
,
NB_RESULT_PAR_PLV AS (
SELECT referenceprel, COUNT(DISTINCT categorie) AS nbcategorieparplv
FROM TEMP_RESULTS
GROUP BY referenceprel
ORDER BY nbcategorieparplv DESC)
,
NB_RESULT_DERNIER_PLV AS (
SELECT LAST_PREL.* , NB_RESULT_PAR_PLV.nbcategorieparplv
FROM LAST_PREL
LEFT JOIN NB_RESULT_PAR_PLV 
ON LAST_PREL.referenceprel = NB_RESULT_PAR_PLV.referenceprel)

SELECT cdreseau, referenceprel, nbcategorieparplv
FROM NB_RESULT_DERNIER_PLV
ORDER BY nbcategorieparplv
"""

nb_resultat_dernier_plv = con.sql (query_nb_resultat_dernier_plv).to_df()
nb_resultat_dernier_plv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

         cdreseau referenceprel  nbcategorieparplv
0       001000460   00100141474                  1
1       002000286   00200199364                  1
2       002001163   00200201767                  1
3       002001660   00200202513                  1
4       004000603   00400141510                  1
...           ...           ...                ...
217536  070001224   07000119286                 14
217537  070000515   07000119439                 14
217538  070000913   07000119686                 14
217539  070000716   07000119842                 14
217540  058000095   05800082560                 15

[217541 rows x 3 columns]

In [ ]:
#max et min résultats à afficher 
max_nb_resultat = nb_resultat_dernier_plv["nbcategorieparplv"].max()
print(f"nombre maximum d'analyse par catégorie par UDI : {max_nb_resultat}")

max_nb_resultat = nb_resultat_dernier_plv["nbcategorieparplv"].min()
print(f"nombre minimum d'analyse par catégorie par UDI : {max_nb_resultat}")

nombre maximum d'analyse par catégorie par UDI : 15
nombre minimum d'analyse par catégorie par UDI : 1

In [ ]:
#BLOC LABORATOIRE
query_test = """ 



"""

test_result = con.sql(query_test).fetchdf()
test_result

    cdreseau referenceprel dernierdateplv plvconformitebacterio plvconformitechimique plvconformitereferencebact plvconformitereferencechim
0  001000677   00100138632     2024-01-08                     C                     C                          C                          C